testing

diff --git a/.github/workflows/kustomize-check.yaml b/.github/workflows/kustomize-check.yaml
--- a/.github/workflows/kustomize-check.yaml
+++ b/.github/workflows/kustomize-check.yaml
@@ -26,6 +26,7 @@ jobs:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
           APPS_CLUSTERS_REGEX: '^apps/clusters/.*/'
           SECURE_CLUSTERS_REGEX: '^secure/.*/'
+          ARGO_PROJECTS_REGEX: '^manifests/devops_infra/argo-projects/base/.*'
         run: |
           set +e
           FAILED=false
@@ -74,6 +75,25 @@ jobs:
               if [ "$FAILED" = true ]; then
                 echo "kustomize build failed in $directory"
               fi
+
+            # Check for argo-projects directory changes
+            elif [[ $file =~ $ARGO_PROJECTS_REGEX ]]; then
+              echo "File '$file' was changed in manifests/devops_infra/argo-projects/base/**/"
+
+              # Check if the file is included in kustomization.yaml
+              if ! grep -q "$(basename "$file")" "$directory/kustomization.yaml"; then
+                echo "Error: $(basename "$file") is not included in $directory/kustomization.yaml."
+                FAILED=true
+              fi
+
+              # Run kustomize build
+              echo "Running kustomize build in $directory"
+              (cd "$directory" && kustomize build .) || FAILED=true
+
+              if [ "$FAILED" = true ]; then
+                echo "kustomize build failed in $directory"
+              fi
+
             else
               echo "File '$file' does not match any known patterns."
             fi
